---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: solr
      annotations: {}
    spec:
      containers:
        - name: solr
          image: iqss/solr-k8s:4.15
          ports:
            - containerPort: 8983
          volumeMounts:
            - name: data
              mountPath: /opt/solr/server/solr/collection1/data
          env:
            - name: SOLR_PORT  # Otherwise, this is wrongfully set by K8s.
              value: "8983"
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -c 8983:8983 /data"]
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: solr
