---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  storageClassName: gp2
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataverse-files
spec:
  storageClassName: gp2
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr
spec:
  storageClassName: gp2
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
